print('Olá Mundo!')
print('Qual o seu nome')
meuNome = input()
print('E bom te conhecer ' + meuNome)
print('O tamanho do seu nome é')
print(len(meuNome))
print('Qual sua idade?')
minhaIdade = input()
print('Você terá ' + str(int(minhaIdade) + 1) + ' anos em um ano')
